# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tasio Mendez
subtitle: Telecom Engineer

author: Tasio Mendez

email: tm.tasio@gmail.com

# Description for metadata. This will appear on Google Results
description: >- # this means to ignore newlines until "baseurl:"
  Hi! · I'm Tasio Mendez - Telecom engineer with passion for new technologies,
  interested in big data, machine learning and cloud computing.

# On top menu description
tagline: >-
  Telecom engineer with passion for new technologies,
  interested in big data, machine learning and cloud computing.

from: Madrid, Spain
location: Milano, Italy

# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo: /assets/img/profile.jpg
accent_image: /assets/img/sidebar.webp

# the subpath of your site, e.g. /blog
baseurl: "/"

# the base hostname & protocol for your site, e.g. http://example.com
url: "https://tasiomendez.github.io"

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang: en

# Build settings
theme: minima

# Collections
collections:
  projects:
    permalink:         /projects/:name/
    output:            true

# Add links to the sidebar.
menu:
  - title:      About
    url:        /about/
  - title:      Projects
    url:        /projects/
  - title:      Résumé
    url:        /cv/
  - title:      Contact
    url:        /contact/

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .jekyll-cache
  - .sass-cache
  - vendor
  - Gemfile
  - Gemfile.lock
